version: "3"
services:
  agent:
    image: acapy-plugin-qa
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "3001:3001"
    # --plugin acapy_plugin_qa
    command: >
      start -it http 0.0.0.0 3000 
        -ot http 
        -e http://agent:3000
        --admin 0.0.0.0 3001 --admin-insecure-mode 
        --no-ledger
        --plugin acapy_plugin_qa
        --plugin acapy_plugin_delegated_qa
        --log-level debug

  echo:
    image: dbluhm/echo-agent:6c22a88
    ports:
      - "3002:3002"
    command: --host 0.0.0.0 --port 3002 --log-level debug

  tests:
    container_name: juggernaut
    build:
      context: .
    environment:
      - WAIT_BEFORE_HOSTS=3
      - WAIT_HOSTS=agent:3000,echo:3002
      - WAIT_HOSTS_TIMEOUT=60
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - AGENT_ENDPOINT=http://agent:3000
      - ADMIN_ENDPOINT=http://agent:3001
      - ECHO_ENDPOINT=http://echo:3002
    depends_on:
      - agent
      - echo
